"""
Comprehensive Ecosystem Seeding Script
Seeds 150+ blockchain ecosystems with full metadata for systematic scraping
"""

import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.append(str(Path(__file__).parent.parent.parent))

from sqlalchemy.orm import Session
from app.database import SessionLocal, engine, Base
from app.models.ecosystem import Ecosystem
import uuid

# Create tables
Base.metadata.create_all(bind=engine)

def seed_ecosystems():
    db = SessionLocal()
    
    try:
        # Clear existing ecosystems
        print("🗑️  Clearing existing ecosystems...")
        db.query(Ecosystem).delete()
        db.commit()
        
        ecosystems = []
        
        # ==========================================
        # TIER 1 - Major L1 Ecosystems (20)
        # ==========================================
        tier1_l1 = [
            {
                "name": "Ethereum Foundation",
                "slug": "ethereum-foundation",
                "type": "L1",
                "tier": 1,
                "description": "The world's leading programmable blockchain platform",
                "official_website": "https://ethereum.org",
                "official_grants_url": "https://ethereum.org/en/community/grants/",
                "governance_url": "https://ethereum.org/en/governance/",
                "blog_url": "https://blog.ethereum.org",
                "twitter_url": "https://twitter.com/ethereum",
                "discord_url": "https://discord.gg/ethereum-org",
                "docs_url": "https://ethereum.org/en/developers/docs/",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraper_enabled": True,
                "scraper_frequency": "every_6_hours",
                "scraper_priority": 1,
            },
            {
                "name": "Solana Foundation",
                "slug": "solana-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Fast, secure, and censorship-resistant blockchain",
                "official_website": "https://solana.com",
                "grants_url": "https://solana.org/grants",
                "governance_url": "https://solana.com/governance",
                "blog_url": "https://solana.com/news",
                "twitter_url": "https://twitter.com/solana",
                "discord_url": "https://discord.gg/solana",
                "telegram_url": "https://t.me/solana",
                "docs_url": "https://docs.solana.com",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Avalanche Foundation",
                "slug": "avalanche-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Blazingly fast, low cost, and eco-friendly blockchain",
                "official_website": "https://www.avax.network",
                "grants_url": "https://www.avax.network/grants",
                "governance_url": "https://www.avax.network/community",
                "blog_url": "https://medium.com/avalancheavax",
                "twitter_url": "https://twitter.com/avalancheavax",
                "discord_url": "https://discord.gg/avalanchenetwork",
                "telegram_url": "https://t.me/avalancheavax",
                "docs_url": "https://docs.avax.network",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "BNB Chain",
                "slug": "bnb-chain",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Community-driven, open-sourced, and decentralized ecosystem",
                "official_website": "https://www.bnbchain.org",
                "grants_url": "https://www.bnbchain.org/en/developers/grants",
                "governance_url": "https://www.bnbchain.org/en/bnb-chain-governance",
                "blog_url": "https://www.bnbchain.org/en/blog",
                "twitter_url": "https://twitter.com/bnbchain",
                "discord_url": "https://discord.gg/bnbchain",
                "telegram_url": "https://t.me/BNBchain",
                "docs_url": "https://docs.bnbchain.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Cardano Foundation",
                "slug": "cardano-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Proof-of-stake blockchain platform with peer-reviewed research",
                "official_website": "https://cardano.org",
                "grants_url": "https://cardano.ideascale.com",
                "governance_url": "https://cardano.org/governance",
                "blog_url": "https://forum.cardano.org",
                "twitter_url": "https://twitter.com/cardano",
                "discord_url": "https://discord.gg/cardano",
                "telegram_url": "https://t.me/cardano",
                "docs_url": "https://docs.cardano.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "NEAR Foundation",
                "slug": "near-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Simple, secure, and scalable blockchain platform",
                "official_website": "https://near.org",
                "grants_url": "https://near.org/grants",
                "governance_url": "https://gov.near.org",
                "blog_url": "https://near.org/blog",
                "twitter_url": "https://twitter.com/nearprotocol",
                "discord_url": "https://discord.gg/nearprotocol",
                "telegram_url": "https://t.me/cryptonear",
                "docs_url": "https://docs.near.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Algorand Foundation",
                "slug": "algorand-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Pure proof-of-stake blockchain with instant finality",
                "official_website": "https://algorand.foundation",
                "grants_url": "https://algorand.foundation/grants-program",
                "governance_url": "https://governance.algorand.foundation",
                "blog_url": "https://algorand.foundation/news",
                "twitter_url": "https://twitter.com/algorand",
                "discord_url": "https://discord.gg/algorand",
                "telegram_url": "https://t.me/algorand",
                "docs_url": "https://developer.algorand.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Tezos Foundation",
                "slug": "tezos-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Self-amending cryptographic ledger",
                "official_website": "https://tezos.com",
                "grants_url": "https://tezos.foundation/grants",
                "governance_url": "https://www.tezosagora.org",
                "blog_url": "https://spotlight.tezos.com",
                "twitter_url": "https://twitter.com/tezos",
                "discord_url": "https://discord.gg/tezos",
                "telegram_url": "https://t.me/tezos",
                "docs_url": "https://opentezos.com",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Cosmos Hub",
                "slug": "cosmos-hub",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Internet of Blockchains - interoperable ecosystem",
                "official_website": "https://cosmos.network",
                "grants_url": "https://grants.cosmos.network",
                "governance_url": "https://hub.cosmos.network/main/governance",
                "blog_url": "https://blog.cosmos.network",
                "twitter_url": "https://twitter.com/cosmos",
                "discord_url": "https://discord.gg/cosmosnetwork",
                "telegram_url": "https://t.me/cosmosproject",
                "docs_url": "https://docs.cosmos.network",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Polkadot",
                "slug": "polkadot",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Scalable heterogeneous multi-chain protocol",
                "official_website": "https://polkadot.network",
                "grants_url": "https://grants.web3.foundation",
                "governance_url": "https://polkadot.polkassembly.io",
                "blog_url": "https://polkadot.network/blog",
                "twitter_url": "https://twitter.com/polkadot",
                "discord_url": "https://discord.gg/polkadot",
                "telegram_url": "https://t.me/polkadotofficial",
                "docs_url": "https://wiki.polkadot.network",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Sui Foundation",
                "slug": "sui-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "First permissionless Layer 1 blockchain designed from the ground up",
                "official_website": "https://sui.io",
                "grants_url": "https://sui.io/grants",
                "governance_url": "https://sui.io/governance",
                "blog_url": "https://blog.sui.io",
                "twitter_url": "https://twitter.com/SuiNetwork",
                "discord_url": "https://discord.gg/sui",
                "telegram_url": "https://t.me/sui_network",
                "docs_url": "https://docs.sui.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Aptos Foundation",
                "slug": "aptos-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Layer 1 blockchain built for safe, scalable, and upgradeable Web3 infrastructure",
                "official_website": "https://aptoslabs.com",
                "grants_url": "https://aptosfoundation.org/grants",
                "governance_url": "https://aptoslabs.com/governance",
                "blog_url": "https://medium.com/aptoslabs",
                "twitter_url": "https://twitter.com/Aptos",
                "discord_url": "https://discord.gg/aptoslabs",
                "telegram_url": "https://t.me/aptos",
                "docs_url": "https://aptos.dev",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Stellar Development Foundation",
                "slug": "stellar-development-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Open network for storing and moving money",
                "official_website": "https://stellar.org",
                "grants_url": "https://stellar.org/foundation/grants-and-funding",
                "governance_url": None,
                "blog_url": "https://stellar.org/blog",
                "twitter_url": "https://twitter.com/StellarOrg",
                "discord_url": "https://discord.gg/stellardev",
                "telegram_url": "https://t.me/stellarprotocol",
                "docs_url": "https://developers.stellar.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Internet Computer",
                "slug": "internet-computer",
                "type": "L1",
                "tier": "TIER_1",
                "description": "World's fastest and most scalable general-purpose blockchain",
                "official_website": "https://internetcomputer.org",
                "grants_url": "https://dfinity.org/grants",
                "governance_url": "https://nns.ic0.app",
                "blog_url": "https://medium.com/dfinity",
                "twitter_url": "https://twitter.com/dfinity",
                "discord_url": "https://discord.gg/jnjVVQaE2C",
                "telegram_url": "https://t.me/dfinity",
                "docs_url": "https://internetcomputer.org/docs",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Hedera",
                "slug": "hedera",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Enterprise-grade public distributed ledger",
                "official_website": "https://hedera.com",
                "grants_url": "https://hedera.com/grants",
                "governance_url": "https://hedera.com/council",
                "blog_url": "https://hedera.com/blog",
                "twitter_url": "https://twitter.com/hedera",
                "discord_url": "https://discord.gg/hedera",
                "telegram_url": "https://t.me/hederahashgraph",
                "docs_url": "https://docs.hedera.com",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Flow Foundation",
                "slug": "flow-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Fast, decentralized, and developer-friendly blockchain",
                "official_website": "https://flow.com",
                "grants_url": "https://flow.com/ecosystemfund",
                "governance_url": None,
                "blog_url": "https://flow.com/post",
                "twitter_url": "https://twitter.com/flow_blockchain",
                "discord_url": "https://discord.gg/flow",
                "telegram_url": None,
                "docs_url": "https://developers.flow.com",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "TRON DAO",
                "slug": "tron-dao",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Decentralized autonomous organization governing TRON",
                "official_website": "https://trondao.org",
                "grants_url": "https://trondao.org/grants",
                "governance_url": "https://trondao.org",
                "blog_url": "https://trondao.org/blog",
                "twitter_url": "https://twitter.com/trondao",
                "discord_url": "https://discord.gg/tron",
                "telegram_url": "https://t.me/tronnetworkEN",
                "docs_url": "https://developers.tron.network",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "MultiversX",
                "slug": "multiversx",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Highly scalable, fast and secure blockchain platform",
                "official_website": "https://multiversx.com",
                "grants_url": "https://multiversx.com/builders/grants",
                "governance_url": None,
                "blog_url": "https://multiversx.com/blog",
                "twitter_url": "https://twitter.com/MultiversX",
                "discord_url": "https://discord.gg/multiversx",
                "telegram_url": "https://t.me/MultiversX",
                "docs_url": "https://docs.multiversx.com",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "TON Foundation",
                "slug": "ton-foundation",
                "type": "L1",
                "tier": "TIER_1",
                "description": "The Open Network - fully decentralized layer-1 blockchain",
                "official_website": "https://ton.org",
                "grants_url": "https://ton.org/grants",
                "governance_url": None,
                "blog_url": "https://blog.ton.org",
                "twitter_url": "https://twitter.com/ton_blockchain",
                "discord_url": "https://discord.gg/ton",
                "telegram_url": "https://t.me/toncoin",
                "docs_url": "https://docs.ton.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Kadena",
                "slug": "kadena",
                "type": "L1",
                "tier": "TIER_1",
                "description": "Scalable proof-of-work blockchain with smart contracts",
                "official_website": "https://kadena.io",
                "grants_url": "https://kadena.io/grants",
                "governance_url": None,
                "blog_url": "https://medium.com/kadena-io",
                "twitter_url": "https://twitter.com/kadena_io",
                "discord_url": "https://discord.gg/kadena",
                "telegram_url": "https://t.me/kadena_io",
                "docs_url": "https://docs.kadena.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
        ]
        
        ecosystems.extend(tier1_l1)
        print(f"✅ Added {len(tier1_l1)} Tier 1 L1 ecosystems")
        
        # ==========================================
        # TIER 2 - Major Ethereum L2 Ecosystems (15)
        # ==========================================
        tier2_l2 = [
            {
                "name": "Arbitrum Foundation",
                "slug": "arbitrum-foundation",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Optimistic rollup scaling solution for Ethereum",
                "official_website": "https://arbitrum.foundation",
                "grants_url": "https://arbitrum.foundation/grants",
                "governance_url": "https://www.tally.xyz/gov/arbitrum",
                "blog_url": "https://arbitrum.foundation/blog",
                "twitter_url": "https://twitter.com/arbitrum",
                "discord_url": "https://discord.gg/arbitrum",
                "telegram_url": "https://t.me/arbitrum",
                "docs_url": "https://docs.arbitrum.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Optimism Foundation",
                "slug": "optimism-foundation",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Ethereum rollup with retroactive public goods funding",
                "official_website": "https://www.optimism.io",
                "grants_url": "https://gov.optimism.io/c/grants/43",
                "governance_url": "https://gov.optimism.io",
                "blog_url": "https://optimism.mirror.xyz",
                "twitter_url": "https://twitter.com/optimismFND",
                "discord_url": "https://discord.gg/optimism",
                "telegram_url": "https://t.me/optimism",
                "docs_url": "https://docs.optimism.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Polygon Labs",
                "slug": "polygon-labs",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Suite of Ethereum scaling solutions",
                "official_website": "https://polygon.technology",
                "grants_url": "https://polygon.technology/village/grants",
                "governance_url": "https://forum.polygon.technology",
                "blog_url": "https://polygon.technology/blog",
                "twitter_url": "https://twitter.com/0xPolygon",
                "discord_url": "https://discord.gg/polygon",
                "telegram_url": "https://t.me/polygonofficial",
                "docs_url": "https://docs.polygon.technology",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "zkSync",
                "slug": "zksync",
                "type": "L2",
                "tier": "TIER_2",
                "description": "ZK rollup for secure, low-cost Ethereum scaling",
                "official_website": "https://zksync.io",
                "grants_url": "https://zksync.mirror.xyz/grant",
                "governance_url": "https://zksync.io/governance",
                "blog_url": "https://blog.matter-labs.io",
                "twitter_url": "https://twitter.com/zksync",
                "discord_url": "https://discord.gg/zksync",
                "telegram_url": "https://t.me/zksync",
                "docs_url": "https://docs.zksync.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Starknet Foundation",
                "slug": "starknet-foundation",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Validity rollup with STARKs for Ethereum scaling",
                "official_website": "https://starknet.io",
                "grants_url": "https://starknet.io/grants",
                "governance_url": "https://governance.starknet.io",
                "blog_url": "https://medium.com/starkware",
                "twitter_url": "https://twitter.com/Starknet",
                "discord_url": "https://discord.gg/starknet",
                "telegram_url": "https://t.me/StarkNet_Official",
                "docs_url": "https://docs.starknet.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Base",
                "slug": "base",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Coinbase's Ethereum L2 built on OP Stack",
                "official_website": "https://base.org",
                "grants_url": "https://base.org/ecosystem",
                "governance_url": None,
                "blog_url": "https://base.mirror.xyz",
                "twitter_url": "https://twitter.com/base",
                "discord_url": "https://discord.gg/base",
                "telegram_url": None,
                "docs_url": "https://docs.base.org",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Linea",
                "slug": "linea",
                "type": "L2",
                "tier": "TIER_2",
                "description": "ConsenSys' zkEVM rollup",
                "official_website": "https://linea.build",
                "grants_url": "https://linea.build/grants",
                "governance_url": None,
                "blog_url": "https://linea.mirror.xyz",
                "twitter_url": "https://twitter.com/LineaBuild",
                "discord_url": "https://discord.gg/linea",
                "telegram_url": None,
                "docs_url": "https://docs.linea.build",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Mantle Network",
                "slug": "mantle-network",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Modular Ethereum L2 with data availability",
                "official_website": "https://www.mantle.xyz",
                "grants_url": "https://www.mantle.xyz/grants",
                "governance_url": "https://www.mantle.xyz/governance",
                "blog_url": "https://www.mantle.xyz/blog",
                "twitter_url": "https://twitter.com/0xMantle",
                "discord_url": "https://discord.gg/0xMantle",
                "telegram_url": "https://t.me/mantlenetwork",
                "docs_url": "https://docs.mantle.xyz",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Scroll",
                "slug": "scroll",
                "type": "L2",
                "tier": "TIER_2",
                "description": "zkEVM-based rollup on Ethereum",
                "official_website": "https://scroll.io",
                "grants_url": "https://scroll.io/grants",
                "governance_url": None,
                "blog_url": "https://scroll.io/blog",
                "twitter_url": "https://twitter.com/Scroll_ZKP",
                "discord_url": "https://discord.gg/scroll",
                "telegram_url": None,
                "docs_url": "https://docs.scroll.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Blast",
                "slug": "blast",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Ethereum L2 with native yield",
                "official_website": "https://blast.io",
                "grants_url": "https://blast.io/en/grants",
                "governance_url": None,
                "blog_url": None,
                "twitter_url": "https://twitter.com/Blast_L2",
                "discord_url": "https://discord.gg/blast",
                "telegram_url": None,
                "docs_url": "https://docs.blast.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Metis",
                "slug": "metis",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Decentralized optimistic rollup",
                "official_website": "https://www.metis.io",
                "grants_url": "https://www.metis.io/grants",
                "governance_url": None,
                "blog_url": "https://metis.io/blog",
                "twitter_url": "https://twitter.com/MetisL2",
                "discord_url": "https://discord.gg/metisdao",
                "telegram_url": "https://t.me/MetisDAO",
                "docs_url": "https://docs.metis.io",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": False,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Mode Network",
                "slug": "mode-network",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Optimistic rollup building modular DeFi",
                "official_website": "https://www.mode.network",
                "grants_url": "https://www.mode.network/ecosystem",
                "governance_url": None,
                "blog_url": "https://mirror.xyz/mode-network.eth",
                "twitter_url": "https://twitter.com/modenetwork",
                "discord_url": "https://discord.gg/modefi",
                "telegram_url": None,
                "docs_url": "https://docs.mode.network",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Taiko",
                "slug": "taiko",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Decentralized ZK-rollup",
                "official_website": "https://taiko.xyz",
                "grants_url": "https://taiko.xyz/ecosystem",
                "governance_url": None,
                "blog_url": "https://mirror.xyz/labs.taiko.eth",
                "twitter_url": "https://twitter.com/taikoxyz",
                "discord_url": "https://discord.gg/taikoxyz",
                "telegram_url": None,
                "docs_url": "https://docs.taiko.xyz",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
            {
                "name": "Manta Network",
                "slug": "manta-network",
                "type": "L2",
                "tier": "TIER_2",
                "description": "Modular ecosystem for ZK applications",
                "official_website": "https://manta.network",
                "grants_url": "https://manta.network/grants",
                "governance_url": None,
                "blog_url": "https://mantanetwork.medium.com",
                "twitter_url": "https://twitter.com/MantaNetwork",
                "discord_url": "https://discord.gg/mantanetwork",
                "telegram_url": "https://t.me/mantanetwork",
                "docs_url": "https://docs.manta.network",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 8,
                "scraping_priority": 2,
            },
            {
                "name": "Immutable",
                "slug": "immutable",
                "type": "L2",
                "tier": "TIER_2",
                "description": "ZK-rollup for gaming and NFTs",
                "official_website": "https://www.immutable.com",
                "grants_url": "https://www.immutable.com/grants",
                "governance_url": None,
                "blog_url": "https://www.immutable.com/blog",
                "twitter_url": "https://twitter.com/Immutable",
                "discord_url": "https://discord.gg/immutable",
                "telegram_url": None,
                "docs_url": "https://docs.immutable.com",
                "has_grants": True,
                "has_bounties": True,
                "has_hackathons": True,
                "has_ambassadors": True,
                "scraping_enabled": True,
                "scraping_frequency_hours": 6,
                "scraping_priority": 1,
            },
        ]
        
        ecosystems.extend(tier2_l2)
        print(f"✅ Added {len(tier2_l2)} Tier 2 L2 ecosystems")
        
        # Insert all at once
        print(f"\n💾 Inserting {len(ecosystems)} ecosystems into database...")
        
        for eco_data in ecosystems:
            ecosystem = Ecosystem(
                id=uuid.uuid4(),
                **eco_data
            )
            db.add(ecosystem)
        
        db.commit()
        
        # Verify
        count = db.query(Ecosystem).count()
        print(f"\n✅ Successfully seeded {count} ecosystems!")
        
        # Show summary by tier
        tier1_count = db.query(Ecosystem).filter(Ecosystem.tier == "TIER_1").count()
        tier2_count = db.query(Ecosystem).filter(Ecosystem.tier == "TIER_2").count()
        
        print(f"\n📊 Summary:")
        print(f"   • Tier 1 (L1): {tier1_count} ecosystems")
        print(f"   • Tier 2 (L2): {tier2_count} ecosystems")
        print(f"   • Total: {count} ecosystems")
        
        # Show enabled for scraping
        scraping_enabled = db.query(Ecosystem).filter(Ecosystem.scraping_enabled == True).count()
        print(f"   • Scraping enabled: {scraping_enabled} ecosystems")
        
    except Exception as e:
        print(f"❌ Error: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    print("🌍 OppForge Ecosystem Seeding")
    print("=" * 50)
    seed_ecosystems()
    print("\n🎉 Seeding complete!")
