#!/usr/bin/env python3
"""
Comprehensive reseed: updates ALL existing seeded opportunities with
real-world comprehensive data — descriptions, requirements, skills, scores, etc.
Also inserts any missing opportunities.
"""
from sqlalchemy import or_
from datetime import datetime, timedelta
from app.models.opportunity import Opportunity
from app.database import SessionLocal
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))


def get_opportunities():
    today = datetime.now()
    return [
        # ───────────────── HACKATHONS ─────────────────
        {
            "title": "ETHGlobal London 2026",
            "url": "https://ethglobal.com/events/london2026",
            "description": "ETHGlobal London is a 36-hour in-person hackathon bringing together 1,500+ builders from the Ethereum ecosystem. Teams compete across multiple sponsor tracks including DeFi, NFTs, DAOs, identity, and infrastructure. The event features workshops from top protocol teams, mentor office hours, and a demo day with industry judges. Past ETHGlobal events have launched projects like Uniswap and PoolTogether.",
            "category": "hackathon",
            "source": "ETHGlobal",
            "reward_pool": "$500,000+",
            "reward_token": "USDC",
            "estimated_value_usd": 500000,
            "deadline": datetime(2026, 4, 12),
            "start_date": datetime(2026, 4, 10),
            "chain": "Ethereum",
            "tags": ["DeFi", "NFT", "DAO", "Infrastructure", "Identity"],
            "mission_requirements": [
                "Build a working prototype during the 36-hour hackathon window",
                "Deploy smart contracts to a supported testnet or mainnet",
                "Submit a 3-minute demo video and public GitHub repository",
                "Team size: 1–5 members; solo hackers welcome",
                "Must use at least one sponsor's technology or API",
                "Project must be started during the event (no pre-built projects)"
            ],
            "required_skills": ["Solidity", "JavaScript", "React", "Ethers.js", "Smart Contracts"],
            "ai_summary": "Premier Ethereum hackathon with $500K+ prizes. Strong for experienced Solidity developers. High competition but excellent networking and sponsor bounty opportunities.",
            "ai_strategy": "Focus on a specific sponsor bounty track rather than the general prize. Arrive with a clear idea and tech stack. Use existing tooling and SDKs to ship faster.",
            "ai_score": 82,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 40,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "ETHGlobal Scaling Ethereum 2026",
            "url": "https://ethglobal.com/events/scaling2026",
            "description": "A virtual hackathon dedicated to Ethereum scaling solutions. Participants build with L2 rollups, zkEVMs, data availability layers, and bridging infrastructure. Bounties from Arbitrum, Optimism, zkSync, Starknet, and Celestia. Ideal for developers passionate about making Ethereum faster and cheaper.",
            "category": "hackathon",
            "source": "ETHGlobal",
            "reward_pool": "$300,000",
            "reward_token": "USDC",
            "estimated_value_usd": 300000,
            "deadline": datetime(2026, 5, 3),
            "start_date": datetime(2026, 4, 19),
            "chain": "Ethereum",
            "tags": ["Layer2", "zkEVM", "Scaling", "Rollups", "Data Availability"],
            "mission_requirements": [
                "Project must focus on Layer 2 scaling, rollups, or data availability",
                "Use at least one sponsor technology (Arbitrum, Optimism, zkSync, Starknet, or Celestia)",
                "Submit working demo with open-source code on GitHub",
                "Present a 3-minute pitch video to judges",
                "Projects must be original work created during the hackathon period",
                "Individual or team submissions accepted (max 5 per team)"
            ],
            "required_skills": ["Solidity", "Rust", "zkProofs", "Rollup Architecture", "Bridge Design"],
            "ai_summary": "Virtual scaling-focused hackathon with $300K bounties from top L2 protocols. Great for ZK and rollup engineers.",
            "ai_strategy": "Pick one L2 ecosystem and go deep. zkSync and Starknet bounties tend to have fewer submissions. Build tooling or developer experience improvements rather than yet another DeFi app.",
            "ai_score": 78,
            "difficulty": "Expert",
            "difficulty_score": 8,
            "win_probability": "Medium",
            "urgency_score": 35,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "Solana Grizzlython 2026",
            "url": "https://solana.com/grizzlython",
            "description": "Solana Foundation's flagship global hackathon with over $5M in prizes and seed funding. Open to developers worldwide, Grizzlython features tracks for DeFi, Gaming, Mobile (Saga), Payments, and DAOs/Network States. Winners receive prize money, mentorship from Solana Labs, and access to accelerator programs. Previous editions launched Marinade Finance, Phantom, and Jupiter.",
            "category": "hackathon",
            "source": "Solana Foundation",
            "reward_pool": "$5,000,000+",
            "reward_token": "USDC",
            "estimated_value_usd": 5000000,
            "deadline": today + timedelta(days=45),
            "start_date": today + timedelta(days=10),
            "chain": "Solana",
            "tags": ["DeFi", "Gaming", "Mobile", "Payments", "DAO"],
            "mission_requirements": [
                "Build and deploy a working application on Solana devnet or mainnet",
                "Submit project via the official hackathon portal with a demo video (max 5 min)",
                "Include a README with setup instructions and architecture overview",
                "Open-source your code on GitHub with an appropriate license",
                "Projects must be new — forks of existing projects are ineligible",
                "Team size: 1–5 members"
            ],
            "required_skills": ["Rust", "Anchor", "TypeScript", "Solana Web3.js", "React"],
            "ai_summary": "Solana's largest hackathon with $5M+ in prizes. Massive opportunity but very competitive. Best for experienced Solana developers or fast learners.",
            "ai_strategy": "The Payments and Mobile tracks typically have fewer submissions. Build something that showcases Solana's speed — sub-second UX. Use Anchor framework for faster development.",
            "ai_score": 88,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 60,
            "trust_score": 98,
            "risk_score": 3,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/solana-sol-logo.svg",
        },
        {
            "title": "Solana DeFi Hackathon",
            "url": "https://solana.com/defi-hack",
            "description": "Specialized DeFi hackathon on Solana focused on building next-generation financial protocols. Tracks include lending/borrowing, DEX aggregation, derivatives/perpetuals, yield optimization, and real-world asset (RWA) tokenization. Sponsored by Jupiter, Marinade, Raydium, and Drift Protocol. Top projects receive direct investment offers from Solana ecosystem VCs.",
            "category": "hackathon",
            "source": "Solana Foundation",
            "reward_pool": "$1,000,000",
            "reward_token": "USDC",
            "estimated_value_usd": 1000000,
            "deadline": today + timedelta(days=28),
            "start_date": today + timedelta(days=3),
            "chain": "Solana",
            "tags": ["DeFi", "Lending", "DEX", "Derivatives", "RWA"],
            "mission_requirements": [
                "Project must be a DeFi application deployed on Solana devnet or mainnet",
                "Integrate with at least one existing Solana DeFi protocol (Jupiter, Raydium, Drift, etc.)",
                "Include security considerations document addressing common DeFi attack vectors",
                "Submit smart contract audit report or self-audit checklist",
                "Demo must show working transactions — not just UI mockups",
                "Provide liquidity/economics documentation for your protocol"
            ],
            "required_skills": ["Rust", "Anchor", "DeFi Protocols", "TypeScript", "Token Programs"],
            "ai_summary": "DeFi-specific Solana hackathon with $1M prizes. Great for developers with DeFi protocol experience. Sponsor bounties from top Solana DeFi protocols.",
            "ai_strategy": "Build on top of existing DEX aggregators like Jupiter. The RWA and derivatives tracks are underserved. Focus on novel use cases rather than cloning existing protocols.",
            "ai_score": 75,
            "difficulty": "Expert",
            "difficulty_score": 7,
            "win_probability": "Medium",
            "urgency_score": 70,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/solana-sol-logo.svg",
        },
        {
            "title": "Gitcoin Grants Round 20",
            "url": "https://gitcoin.co/grants",
            "description": "Gitcoin's quadratic funding round distributes $2M in matching funds to public goods projects across the Ethereum ecosystem. Categories include Developer Tools, Education, DeFi Infrastructure, Climate Solutions, and Community Growth. Projects receive funding proportional to the number of unique donors, incentivizing broad community support. Apply as a grant recipient or contribute as a donor to shape Web3 public goods.",
            "category": "grant",
            "source": "Gitcoin",
            "reward_pool": "$2,000,000 matching pool",
            "reward_token": "DAI",
            "estimated_value_usd": 2000000,
            "deadline": today + timedelta(days=14),
            "chain": "Multi-chain",
            "tags": ["Public Goods", "Dev Tools", "Climate", "Education", "Quadratic Funding"],
            "mission_requirements": [
                "Project must qualify as a public good (open-source, non-extractive)",
                "Create a grant profile on Gitcoin Explorer with description, team, and roadmap",
                "Provide proof of prior work or a working prototype",
                "Must pass Gitcoin's Passport identity verification (Sybil resistance)",
                "Regular progress updates required during and after the funding round",
                "Projects must be non-profit or have a clear public goods component"
            ],
            "required_skills": ["Open Source Development", "Community Building", "Smart Contracts", "Technical Writing"],
            "ai_summary": "Quadratic funding round with $2M matching. Best for open-source projects with existing community. Number of unique donors matters more than donation size.",
            "ai_strategy": "Focus on community outreach to maximize unique donor count. Even $1 donations count significantly in quadratic funding. Share on Twitter, Discord, and Farcaster. Have a clear, compelling grant page with visuals.",
            "ai_score": 70,
            "difficulty": "Beginner",
            "difficulty_score": 3,
            "win_probability": "High",
            "urgency_score": 80,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "Uniswap Foundation Grants Program",
            "url": "https://uniswapfoundation.org/grants",
            "description": "The Uniswap Foundation awards grants up to $250K for projects building on Uniswap v4. Priority areas include custom hooks development, DeFi protocol integrations, governance tooling, analytics dashboards, and educational content. Rolling applications with quarterly review cycles. The Foundation provides technical mentorship, code reviews, and ecosystem introductions alongside funding.",
            "category": "grant",
            "source": "Uniswap",
            "reward_pool": "Up to $250,000",
            "reward_token": "USDC",
            "estimated_value_usd": 250000,
            "deadline": None,
            "chain": "Ethereum",
            "tags": ["DeFi", "DEX", "Uniswap", "Governance", "Hooks"],
            "mission_requirements": [
                "Submit a detailed proposal with problem statement, solution, timeline, and budget",
                "Team must have relevant technical experience (link GitHub profiles)",
                "Project must directly benefit the Uniswap ecosystem or its users",
                "Milestone-based funding: deliverables defined upfront with regular check-ins",
                "Open-source requirement: all funded code must be publicly available",
                "Quarterly progress reports to the Uniswap Foundation"
            ],
            "required_skills": ["Solidity", "Uniswap v4 Hooks", "DeFi Architecture", "React", "The Graph"],
            "ai_summary": "Rolling grants up to $250K from Uniswap Foundation. Great for experienced DeFi developers. Hooks development is the highest priority track.",
            "ai_strategy": "Build a novel Uniswap v4 hook that solves a real problem. The Foundation loves projects that increase Uniswap volume or improve user experience. Start with a small prototype before applying.",
            "ai_score": 72,
            "difficulty": "Expert",
            "difficulty_score": 8,
            "win_probability": "Medium",
            "urgency_score": 20,
            "trust_score": 98,
            "risk_score": 3,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/uniswap-uni-logo.svg",
        },
        {
            "title": "Aave Grants DAO Q1 2026",
            "url": "https://aavegrants.org",
            "description": "Aave Grants DAO allocates $500K quarterly for ecosystem development. Priority areas this quarter: GHO stablecoin integrations, risk management dashboards, cross-chain lending tools, and governance participation improvements. Proposals are reviewed weekly by the grants committee. Successful applicants receive milestone-based payments in USDC and may receive AAVE token bonuses for exceptional delivery.",
            "category": "grant",
            "source": "Aave",
            "reward_pool": "$500,000",
            "reward_token": "USDC + AAVE",
            "estimated_value_usd": 500000,
            "deadline": today + timedelta(days=30),
            "chain": "Ethereum",
            "tags": ["DeFi", "Lending", "GHO", "Risk Management", "Cross-chain"],
            "mission_requirements": [
                "Submit a structured proposal on the Aave governance forum",
                "Include technical specification, team background, and detailed budget breakdown",
                "Project must integrate with or improve the Aave Protocol (v3 or GHO)",
                "Milestone-based delivery with payment at each milestone completion",
                "Security audit required for any smart contract work (can be funded by the grant)",
                "Present progress at Aave community calls (monthly)"
            ],
            "required_skills": ["Solidity", "Aave Protocol", "DeFi", "Risk Analysis", "TypeScript"],
            "ai_summary": "Quarterly grants from Aave DAO. GHO integrations and risk tooling are the hottest tracks. Well-structured program with clear expectations.",
            "ai_strategy": "GHO integrations have the highest approval rate. Build a working proof-of-concept before submitting. Reference existing Aave Improvement Proposals (AIPs) in your application to show ecosystem awareness.",
            "ai_score": 68,
            "difficulty": "Expert",
            "difficulty_score": 7,
            "win_probability": "Medium",
            "urgency_score": 55,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/aave-aave-logo.svg",
        },
        {
            "title": "Arbitrum Stylus Hackathon",
            "url": "https://arbitrum.io/stylus-hack",
            "description": "Build next-generation smart contracts on Arbitrum using Stylus — write in Rust, C, or C++ and deploy to the same EVM chain alongside Solidity contracts. $400K in prizes across categories: DeFi, Gaming, Developer Tooling, and Creative Use Cases. Stylus contracts are 10–100x cheaper on compute-heavy operations. Arbitrum Foundation provides starter templates, documentation, and office hours with the Stylus core team.",
            "category": "hackathon",
            "source": "Arbitrum",
            "reward_pool": "$400,000",
            "reward_token": "ARB + USDC",
            "estimated_value_usd": 400000,
            "deadline": today + timedelta(days=42),
            "start_date": today + timedelta(days=14),
            "chain": "Arbitrum",
            "tags": ["Layer2", "Rust", "Stylus", "Smart Contracts", "WASM"],
            "mission_requirements": [
                "Deploy at least one Stylus smart contract on Arbitrum Sepolia or mainnet",
                "Use Rust, C, or C++ for the on-chain component (Solidity helper contracts allowed)",
                "Submit source code on GitHub with build and deployment instructions",
                "Create a 3-minute demo video showing the application in action",
                "Document the gas savings compared to equivalent Solidity implementation",
                "Teams of 1–5; must register on the hackathon portal"
            ],
            "required_skills": ["Rust", "WASM", "Smart Contracts", "Arbitrum", "Systems Programming"],
            "ai_summary": "Niche Stylus hackathon on Arbitrum. Lower competition since Rust/WASM smart contract developers are rare. $400K prizes.",
            "ai_strategy": "Stylus is new — the bar for winning is lower than typical Solidity hackathons. Port a computationally expensive algorithm (ML inference, image processing, etc.) to a Stylus contract to showcase the gas savings.",
            "ai_score": 76,
            "difficulty": "Expert",
            "difficulty_score": 8,
            "win_probability": "High",
            "urgency_score": 50,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/arbitrum-arb-logo.svg",
        },
        {
            "title": "Optimism RetroPGF Round 5",
            "url": "https://optimism.io/retropgf",
            "description": "Retroactive Public Goods Funding (RetroPGF) rewards builders who have already created impact in the Optimism ecosystem. Unlike traditional grants, RetroPGF pays for past contributions — so you don't need permission to build. $30M distributed based on community votes from badgeholders. Past recipients include Protocol Guild, L2BEAT, ethers.js, and Remix IDE. Categories: Infrastructure, Tooling, Education, and Governance.",
            "category": "grant",
            "source": "Optimism",
            "reward_pool": "$30,000,000",
            "reward_token": "OP",
            "estimated_value_usd": 30000000,
            "deadline": today + timedelta(days=60),
            "chain": "Optimism",
            "tags": ["Public Goods", "RetroPGF", "Layer2", "Impact", "Governance"],
            "mission_requirements": [
                "Project must have demonstrable impact on the Optimism Collective or broader Ethereum ecosystem",
                "Create a detailed RetroPGF application describing your contributions and their impact",
                "Provide metrics: GitHub stars, downloads, users served, TVL impacted, etc.",
                "Applications reviewed and voted on by ~150+ badgeholders",
                "No application fee; open to individuals, teams, and organizations",
                "Must link all relevant repositories, websites, and social accounts for verification"
            ],
            "required_skills": ["Open Source Development", "Community Building", "Technical Documentation"],
            "ai_summary": "Massive $30M retroactive funding round. Ideal if you've already built something impactful. Community-voted, no gatekeepers.",
            "ai_strategy": "You need existing impact to win. If you haven't built for Optimism yet, start contributing now and apply to Round 6. For this round, document ALL your contributions meticulously and get endorsements from ecosystem members.",
            "ai_score": 85,
            "difficulty": "Intermediate",
            "difficulty_score": 5,
            "win_probability": "Medium",
            "urgency_score": 40,
            "trust_score": 99,
            "risk_score": 2,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/optimism-ethereum-op-logo.svg",
        },
        {
            "title": "Base Onchain Summer 2026",
            "url": "https://base.org/summer",
            "description": "Base's annual 6-week virtual hackathon invites developers to build consumer-facing onchain applications. $1M+ in prizes across Consumer Social, Onchain Gaming, Commerce, and Creator Tools tracks. Base provides gas credits, technical mentorship, and warm intros to Coinbase Ventures for top projects. Previous winners include Friend.tech, Farcaster clients, and onchain art platforms.",
            "category": "hackathon",
            "source": "Base",
            "reward_pool": "$1,000,000+",
            "reward_token": "USDC + ETH",
            "estimated_value_usd": 1000000,
            "deadline": today + timedelta(days=50),
            "start_date": today + timedelta(days=8),
            "chain": "Base",
            "tags": ["Consumer Apps", "Social", "Gaming", "Commerce", "Creator Tools"],
            "mission_requirements": [
                "Application must be deployed on Base mainnet or testnet",
                "Focus on consumer-facing UX — apps your non-crypto friends would use",
                "Submit via the official portal with a live demo link and GitHub repo",
                "Include a 2-minute walkthrough video",
                "Must use native Base infrastructure (no bridged-only solutions)",
                "Team or individual submissions welcome; max 5 per team"
            ],
            "required_skills": ["Solidity", "React/Next.js", "Ethers.js/Viem", "UI/UX Design", "Base"],
            "ai_summary": "Consumer-focused hackathon on Base. $1M+ prizes. Judges value polish and real-user focus over technical complexity.",
            "ai_strategy": "Think 'what would my mom use?' rather than 'what's technically impressive.' Social and gaming tracks have the highest engagement. Use account abstraction to hide wallet complexity.",
            "ai_score": 80,
            "difficulty": "Intermediate",
            "difficulty_score": 5,
            "win_probability": "Medium",
            "urgency_score": 55,
            "trust_score": 98,
            "risk_score": 3,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "zkSync Builder Program Q1",
            "url": "https://zksync.io/builders",
            "description": "zkSync Era's Builder Program provides $750K in grants for teams building on the zkEVM. Focus areas: account abstraction and paymasters, ZK-native applications (privacy, identity, gaming), developer tooling, and DeFi protocols. Grants range from $10K–$100K based on project scope. Includes technical support from Matter Labs engineers, audit credits, and marketing amplification.",
            "category": "grant",
            "source": "zkSync",
            "reward_pool": "$750,000",
            "reward_token": "USDC",
            "estimated_value_usd": 750000,
            "deadline": today + timedelta(days=38),
            "chain": "zkSync",
            "tags": ["zkEVM", "Account Abstraction", "ZK", "Layer2", "Paymasters"],
            "mission_requirements": [
                "Submit a proposal with technical architecture, timeline, team bio, and budget",
                "Project must deploy on zkSync Era (mainnet or testnet)",
                "Demonstrate understanding of zkSync-specific features (native AA, paymasters, etc.)",
                "Milestone-based disbursement with monthly progress reviews",
                "Final deliverables must be open-source with documentation",
                "Present results at zkSync community showcase"
            ],
            "required_skills": ["Solidity", "zkSync SDK", "Account Abstraction", "TypeScript", "ZK Concepts"],
            "ai_summary": "Grant program focused on zkSync-native features. $10K–$100K per project. Account abstraction and paymaster projects are prioritized.",
            "ai_strategy": "Build a paymaster that lets users pay gas in any ERC-20 token or build gasless onboarding flows. These are high-priority for zkSync and have fewer applicants than DeFi proposals.",
            "ai_score": 71,
            "difficulty": "Expert",
            "difficulty_score": 7,
            "win_probability": "Medium",
            "urgency_score": 50,
            "trust_score": 92,
            "risk_score": 8,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/zksync-zk-logo.svg",
        },
        {
            "title": "Polygon Village Accelerator Batch 3",
            "url": "https://polygon.technology/village",
            "description": "A 12-week accelerator program by Polygon Labs with $100K equity-free investment per team, plus $150K in infrastructure credits. Includes weekly mentorship from Polygon engineers, product workshops, fundraising bootcamp, and a Demo Day with top Web3 VCs. Open to early-stage startups building on Polygon PoS, Polygon zkEVM, or Polygon CDK. Past batches produced 40+ funded startups.",
            "category": "grant",
            "source": "Polygon",
            "reward_pool": "$100,000 + $150K credits",
            "reward_token": "USDC",
            "estimated_value_usd": 100000,
            "deadline": today + timedelta(days=25),
            "chain": "Polygon",
            "tags": ["Accelerator", "Startups", "Investment", "Mentorship", "zkEVM"],
            "mission_requirements": [
                "Team must have 2–5 members with at least one technical co-founder",
                "Working prototype or MVP required (idea-stage not accepted)",
                "Must be building on Polygon PoS, zkEVM, or CDK",
                "Commit to 12 weeks of full-time or near-full-time participation",
                "Submit pitch deck, product demo, and team background",
                "Present at Demo Day to investors and ecosystem partners"
            ],
            "required_skills": ["Solidity", "Product Development", "Polygon SDK", "Business Strategy", "Pitching"],
            "ai_summary": "12-week accelerator with $100K + $150K credits. Great for teams with an MVP. High commitment but excellent mentorship and VC access.",
            "ai_strategy": "Have a clear product-market fit story. Show traction metrics if you have them. The program values execution speed and founder quality over technical novelty.",
            "ai_score": 74,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 60,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/polygon-matic-logo.svg",
        },
        {
            "title": "Avalanche Multiverse Incentive Program",
            "url": "https://avax.network/multiverse",
            "description": "Avalanche Foundation's $4M program to bootstrap Subnet development. Provides gas subsidies, validator incentives, technical architecture support, and go-to-market assistance. Designed for teams building application-specific blockchains (Subnets) on Avalanche. Ideal for gaming studios, enterprise applications, and DeFi protocols that need custom execution environments.",
            "category": "grant",
            "source": "Avalanche",
            "reward_pool": "$4,000,000",
            "reward_token": "AVAX",
            "estimated_value_usd": 4000000,
            "deadline": None,
            "chain": "Avalanche",
            "tags": ["Subnets", "Infrastructure", "Gas Subsidies", "Enterprise", "Custom Chains"],
            "mission_requirements": [
                "Project must deploy or plan to deploy an Avalanche Subnet",
                "Submit a proposal with Subnet architecture design and use case justification",
                "Demonstrate why a Subnet is necessary (vs. deploying on C-Chain)",
                "Provide a 6-month roadmap with user growth and TVL targets",
                "Commit to running or coordinating a minimum number of validators",
                "Participate in monthly ecosystem check-ins with Avalanche Foundation"
            ],
            "required_skills": ["Go", "Subnet Architecture", "Validator Operations", "Avalanche SDK", "DevOps"],
            "ai_summary": "Large-scale Subnet incentive program. Best for teams building custom L1s on Avalanche. Ongoing program with no fixed deadline.",
            "ai_strategy": "Gaming and enterprise use cases have the highest approval rate. Show why your application needs its own chain. Avalanche Foundation loves projects that bring new users to the ecosystem.",
            "ai_score": 65,
            "difficulty": "Expert",
            "difficulty_score": 9,
            "win_probability": "Low",
            "urgency_score": 15,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/avalanche-avax-logo.svg",
        },
        {
            "title": "Superteam Earn: DeFi Dashboard Bounty",
            "url": "https://earn.superteam.fun/listings/bounty/defi-dashboard",
            "description": "Superteam Earn offers a $15K bounty for building a comprehensive DeFi analytics dashboard on Solana. Must support multi-chain portfolio tracking, real-time price feeds, impermanent loss calculators, and yield farming analytics. The dashboard should aggregate data from Jupiter, Raydium, Orca, Marinade, and other major Solana DeFi protocols. Clean, responsive UI required.",
            "category": "bounty",
            "source": "Superteam",
            "reward_pool": "$15,000",
            "reward_token": "USDC",
            "estimated_value_usd": 15000,
            "deadline": today + timedelta(days=20),
            "chain": "Solana",
            "tags": ["DeFi", "Analytics", "Dashboard", "Multi-chain", "Portfolio"],
            "mission_requirements": [
                "Full-stack web application with responsive design (mobile + desktop)",
                "Integrate with at least 5 Solana DeFi protocols for real-time data",
                "Include portfolio tracking, P&L calculations, and yield analytics",
                "Impermanent loss calculator for LP positions",
                "Wallet connection via Phantom, Solflare, and Backpack",
                "Deploy to a public URL for testing; submit source code on GitHub"
            ],
            "required_skills": ["React/Next.js", "Solana Web3.js", "DeFi Protocols", "Data Visualization", "API Integration"],
            "ai_summary": "Single-winner $15K bounty for a Solana DeFi dashboard. Clear requirements and scope. Great for frontend developers with DeFi knowledge.",
            "ai_strategy": "Focus on UX polish and accurate data. Judges will compare against existing tools like Step Finance and Sonar Watch. Add one unique feature they don't have.",
            "ai_score": 62,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 65,
            "trust_score": 88,
            "risk_score": 10,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/solana-sol-logo.svg",
        },
        {
            "title": "Farcaster Frames Development Grant",
            "url": "https://farcaster.xyz/frames-grant",
            "description": "Farcaster is offering $50K in grants for innovative Frames applications — interactive mini-apps embedded directly in the social feed. Build social games, commerce experiences, voting systems, or creative tools that work natively in Warpcast and other Farcaster clients. Frames run on Base and can interact with any onchain data. Previous Frame hits include /polls, /mint, and /trade.",
            "category": "grant",
            "source": "Farcaster",
            "reward_pool": "$50,000",
            "reward_token": "USDC",
            "estimated_value_usd": 50000,
            "deadline": today + timedelta(days=32),
            "chain": "Base",
            "tags": ["Social", "Frames", "Apps", "Decentralized Social", "Warpcast"],
            "mission_requirements": [
                "Build a functional Farcaster Frame with at least 3 interactive screens",
                "Deploy the Frame backend and register it on a public URL",
                "Must work in Warpcast and at least one other Farcaster client",
                "Include onchain interactions (minting, voting, trading, etc.) on Base",
                "Submit a demo cast showing the Frame in action with at least 50 interactions",
                "Open-source the Frame code with setup documentation"
            ],
            "required_skills": ["Next.js", "Farcaster SDK", "Base/Ethereum", "API Design", "Social UX"],
            "ai_summary": "Frames grant from Farcaster. $50K for interactive social mini-apps. Lower competition than traditional hackathons. Social distribution is built in.",
            "ai_strategy": "Build something viral — games and interactive experiences spread fastest on Farcaster. Study what existing popular Frames do well. Optimize for mobile UX since most Warpcast users are on phones.",
            "ai_score": 69,
            "difficulty": "Intermediate",
            "difficulty_score": 5,
            "win_probability": "High",
            "urgency_score": 50,
            "trust_score": 85,
            "risk_score": 12,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "Immunefi Security Research Grant",
            "url": "https://immunefi.com/research-grant",
            "description": "Immunefi — the leading Web3 bug bounty platform — offers $100K in grants for novel security research. Focus areas: MEV attack vectors, cross-chain bridge vulnerabilities, smart contract formal verification, and DeFi economic exploit modeling. Research is published on Immunefi's blog and credited to researchers. Past grantees have uncovered critical vulnerabilities saving $100M+ in user funds.",
            "category": "grant",
            "source": "Immunefi",
            "reward_pool": "$100,000",
            "reward_token": "USDC",
            "estimated_value_usd": 100000,
            "deadline": today + timedelta(days=55),
            "chain": "Multi-chain",
            "tags": ["Security", "Research", "MEV", "Bridges", "Formal Verification"],
            "mission_requirements": [
                "Submit a research proposal with hypothesis, methodology, and timeline",
                "Focus on one of the priority areas: MEV, bridges, formal verification, or economic exploits",
                "Produce a publishable research paper with actionable findings",
                "Responsible disclosure: any vulnerabilities found must be reported through Immunefi's platform",
                "Peer review by Immunefi's security team before publication",
                "Present findings at a security conference or webinar"
            ],
            "required_skills": ["Smart Contract Security", "Formal Verification", "MEV Analysis", "Solidity", "Python"],
            "ai_summary": "Prestigious security research grant from Immunefi. $100K for novel vulnerability research. High impact and reputation building.",
            "ai_strategy": "Cross-chain bridge security research has the highest demand. Combine formal verification with empirical testing. Reference recent bridge exploits (Nomad, Wormhole, Ronin) and show how your research prevents similar attacks.",
            "ai_score": 67,
            "difficulty": "Expert",
            "difficulty_score": 9,
            "win_probability": "Low",
            "urgency_score": 30,
            "trust_score": 98,
            "risk_score": 3,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "Monad Testnet Incentives Program",
            "url": "https://monad.xyz/testnet",
            "description": "Monad — the high-performance parallelized EVM blockchain — is distributing $2M to developers building on its testnet. Monad processes 10,000+ TPS with 1-second finality while maintaining full EVM compatibility. Categories: DeFi protocols, gaming, social apps, and developer tooling. Early builders may qualify for the eventual mainnet airdrop. Monad has raised $225M from Paradigm and Dragonfly.",
            "category": "testnet",
            "source": "Monad",
            "reward_pool": "$2,000,000",
            "reward_token": "TBD",
            "estimated_value_usd": 2000000,
            "deadline": today + timedelta(days=90),
            "chain": "Monad",
            "tags": ["Testnet", "EVM", "High Performance", "Early Access", "Parallelized"],
            "mission_requirements": [
                "Deploy a smart contract or dApp on Monad testnet",
                "Project must demonstrate Monad's performance advantages (parallelism, speed)",
                "Submit on the developer portal with contract addresses and demo URL",
                "Create documentation or a tutorial about building on Monad",
                "Engage with the Monad developer community (Discord, Twitter)",
                "Open to individuals and teams; no team size restriction"
            ],
            "required_skills": ["Solidity", "EVM Development", "React", "Ethers.js/Viem", "Performance Optimization"],
            "ai_summary": "Early-access testnet program with $2M rewards. Full EVM compatibility means you can port existing projects easily. Potential airdrop upside.",
            "ai_strategy": "Port an existing EVM project to Monad and showcase the speed difference. Build something that's impossible on slow chains — real-time onchain games, high-frequency DeFi. Being early matters: start now for potential airdrop eligibility.",
            "ai_score": 79,
            "difficulty": "Beginner",
            "difficulty_score": 3,
            "win_probability": "High",
            "urgency_score": 25,
            "trust_score": 85,
            "risk_score": 15,
            "risk_level": "Low",
            "risk_flags": ["Mainnet not yet launched", "Token not yet distributed"],
            "logo_url": None,
        },
        {
            "title": "Berachain Build-a-Bera Hackathon",
            "url": "https://berachain.com/hackathon",
            "description": "Berachain's flagship hackathon built around its novel Proof of Liquidity (PoL) consensus mechanism. $500K in prizes across DeFi, NFTs, Gaming, and PoL Innovation tracks. Berachain runs an EVM-compatible chain where staking and liquidity provision are unified. The hackathon encourages creative use of BGT (governance token), HONEY (stablecoin), and the native DEX. Strong community with active Discord support.",
            "category": "hackathon",
            "source": "Berachain",
            "reward_pool": "$500,000",
            "reward_token": "USDC + HONEY",
            "estimated_value_usd": 500000,
            "deadline": today + timedelta(days=40),
            "start_date": today + timedelta(days=12),
            "chain": "Berachain",
            "tags": ["DeFi", "NFT", "Gaming", "PoL", "Proof of Liquidity"],
            "mission_requirements": [
                "Deploy on Berachain testnet (Artio) or mainnet",
                "Leverage at least one Berachain-native concept: BGT, HONEY, PoL, or BEX",
                "Submit project with README, demo video (3 min max), and GitHub link",
                "PoL Innovation track requires integration with the Berachain reward vault system",
                "Solo or team (max 5 members); must register before the hackathon starts",
                "Attend at least one workshop or office hour session during the event"
            ],
            "required_skills": ["Solidity", "Berachain SDK", "DeFi", "React", "Token Design"],
            "ai_summary": "Novel hackathon centered on Proof of Liquidity. $500K prizes. The PoL Innovation track has the fewest submissions and highest per-capita prizes.",
            "ai_strategy": "Build around BGT delegation and reward vaults. The PoL Innovation track is where Berachain Foundation pays the most attention. Study how validators and liquidity interact in the PoL model.",
            "ai_score": 73,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 55,
            "trust_score": 82,
            "risk_score": 18,
            "risk_level": "Low",
            "risk_flags": ["Relatively new chain", "Testnet may have instability"],
            "logo_url": None,
        },
        {
            "title": "Blast Big Bang Competition Phase 2",
            "url": "https://blast.io/bigbang",
            "description": "Blast's $10M Big Bang competition funds projects building on its native yield chain. Blast automatically earns yield on ETH and stablecoins held by smart contracts, and shares gas revenue with dApps. Phase 2 focuses on scaling existing projects and launching new ones. Categories: DeFi, NFTs/Gaming, SocialFi, and Infrastructure. Winners receive BLAST tokens, partnership support, and Blast Foundation marketing.",
            "category": "hackathon",
            "source": "Blast",
            "reward_pool": "$10,000,000",
            "reward_token": "BLAST",
            "estimated_value_usd": 10000000,
            "deadline": today + timedelta(days=65),
            "start_date": today + timedelta(days=5),
            "chain": "Blast",
            "tags": ["Native Yield", "Gas Revenue", "DeFi", "Layer2", "SocialFi"],
            "mission_requirements": [
                "Deploy on Blast mainnet with working smart contracts",
                "Integrate with Blast's native yield: auto-rebasing ETH and USDB",
                "Implement gas revenue sharing via Blast's Gas API",
                "Submit application with live dApp URL, smart contract addresses, and metrics",
                "Present user traction metrics (TVL, users, transactions) for Phase 2",
                "Open to new and existing Blast projects"
            ],
            "required_skills": ["Solidity", "Blast SDK", "DeFi", "React", "Gas Optimization"],
            "ai_summary": "Massive $10M competition on Blast. Requires live deployment and traction. Best for teams that can ship fast and attract users.",
            "ai_strategy": "Build something that creatively uses native yield. The SocialFi track is underserved. Focus on user acquisition metrics — the judges weigh traction heavily in Phase 2.",
            "ai_score": 77,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 45,
            "trust_score": 80,
            "risk_score": 20,
            "risk_level": "Low",
            "risk_flags": ["Token price volatility may affect real prize value"],
            "logo_url": "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
        },
        {
            "title": "DoraHacks Web3 For Good",
            "url": "https://dorahacks.io/web3-for-good",
            "description": "DoraHacks' impact-driven hackathon with $200K in prizes for blockchain solutions to real-world problems. Categories: Climate & Sustainability (carbon credits, supply chain transparency), Healthcare (medical data, drug traceability), Education (credentialing, knowledge sharing), and Financial Inclusion (micro-lending, remittances, digital identity). Projects are judged on real-world applicability, technical implementation, and potential for adoption.",
            "category": "hackathon",
            "source": "DoraHacks",
            "reward_pool": "$200,000",
            "reward_token": "USDC",
            "estimated_value_usd": 200000,
            "deadline": today + timedelta(days=33),
            "start_date": today + timedelta(days=5),
            "chain": "Multi-chain",
            "tags": ["Social Impact", "Climate", "Health", "Education", "Financial Inclusion"],
            "mission_requirements": [
                "Project must address a real-world problem in one of the four categories",
                "Working prototype with at least one onchain component",
                "Impact assessment document explaining who benefits and how",
                "Submit via DoraHacks BUIDL platform with demo and source code",
                "Team presentation (5 min pitch + 3 min Q&A) to judges panel",
                "Open to all chains; no chain-specific requirement"
            ],
            "required_skills": ["Smart Contracts", "Full-Stack Development", "Impact Assessment", "UI/UX", "Research"],
            "ai_summary": "Impact-focused hackathon with $200K. Lower competition than pure DeFi hackathons. Judges value real-world applicability over pure tech.",
            "ai_strategy": "Financial Inclusion track has the strongest judge interest. Build for a specific community or geography (e.g., remittances for X country). Partner with an NGO or community org to strengthen your application.",
            "ai_score": 64,
            "difficulty": "Intermediate",
            "difficulty_score": 5,
            "win_probability": "Medium",
            "urgency_score": 55,
            "trust_score": 88,
            "risk_score": 8,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": None,
        },
        {
            "title": "MakerDAO Endgame Grants",
            "url": "https://makerdao.com/endgame-grants",
            "description": "MakerDAO's $1M grant fund supports the Endgame transition — restructuring MakerDAO into a constellation of SubDAOs. Grants cover SubDAO development, governance infrastructure, risk management tools, DAI/USDS integrations, and RWA (Real World Asset) onboarding tools. This is a critical phase for MakerDAO as it decentralizes into purpose-specific SubDAOs. Funded by MakerDAO governance vote.",
            "category": "grant",
            "source": "MakerDAO",
            "reward_pool": "$1,000,000",
            "reward_token": "DAI",
            "estimated_value_usd": 1000000,
            "deadline": today + timedelta(days=70),
            "chain": "Ethereum",
            "tags": ["DAO", "Governance", "DeFi", "Endgame", "SubDAO", "RWA"],
            "mission_requirements": [
                "Submit proposal to MakerDAO governance forum with detailed scope and budget",
                "Project must contribute to the Endgame transition or SubDAO infrastructure",
                "Technical proposals need architecture documentation and security assessment",
                "Governance proposals need community champion and delegate endorsements",
                "Milestone-based payments with governance oversight",
                "Report on deliverables at MakerDAO governance calls"
            ],
            "required_skills": ["Solidity", "DAO Governance", "DeFi", "MakerDAO Protocol", "Technical Writing"],
            "ai_summary": "$1M in grants for MakerDAO's Endgame transition. Deep protocol knowledge required. High impact on one of DeFi's largest protocols.",
            "ai_strategy": "SubDAO tooling is the least competitive category. Build governance dashboards, voting analytics, or delegate management tools. Having an existing presence in MakerDAO's forum significantly helps.",
            "ai_score": 60,
            "difficulty": "Expert",
            "difficulty_score": 8,
            "win_probability": "Low",
            "urgency_score": 25,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/maker-mkr-logo.svg",
        },
        {
            "title": "Compound Grants Program 2.0",
            "url": "https://compoundgrants.org",
            "description": "Compound Finance's grants program distributes $500K for ecosystem growth. Priority areas: Compound v3 (Comet) integrations, governance participation tools, risk analytics dashboards, cross-chain COMP governance, and educational content. Rolling applications reviewed biweekly. Grants range from $5K for small tools to $100K for major protocol integrations. The program has funded 100+ projects across 3 years.",
            "category": "grant",
            "source": "Compound",
            "reward_pool": "$500,000",
            "reward_token": "USDC",
            "estimated_value_usd": 500000,
            "deadline": None,
            "chain": "Ethereum",
            "tags": ["DeFi", "Lending", "Governance", "Analytics", "Cross-chain"],
            "mission_requirements": [
                "Submit application on Compound Grants portal with scope, timeline, and budget",
                "Focus on one of the priority categories (v3 integrations, governance, analytics)",
                "Provide relevant experience: GitHub profile, previous projects, team background",
                "Milestone deliverables agreed upfront with grants committee",
                "Funded code must be open-source and well-documented",
                "Participation in at least one Compound governance call per quarter"
            ],
            "required_skills": ["Solidity", "Compound Protocol", "React", "Data Analytics", "TypeScript"],
            "ai_summary": "Rolling grants up to $100K from Compound. Established program with clear process. Good for small teams or solo developers.",
            "ai_strategy": "Analytics and governance tools have the fastest approval times. Build a working prototype before applying. Reference specific Compound governance proposals that your tool addresses.",
            "ai_score": 58,
            "difficulty": "Intermediate",
            "difficulty_score": 6,
            "win_probability": "Medium",
            "urgency_score": 15,
            "trust_score": 95,
            "risk_score": 5,
            "risk_level": "Low",
            "risk_flags": [],
            "logo_url": "https://cryptologos.cc/logos/compound-comp-logo.svg",
        },
    ]


def main():
    db = SessionLocal()
    opportunities = get_opportunities()

    print("🔄 Comprehensive reseed: updating all seeded opportunities...")
    print("=" * 60)

    updated = 0
    added = 0
    skipped = 0

    for opp_data in opportunities:
        url = opp_data["url"]
        existing = db.query(Opportunity).filter(Opportunity.url == url).first()

        # Fields to always update
        update_fields = [
            "description", "category", "source", "reward_pool", "reward_token",
            "estimated_value_usd", "deadline", "start_date", "chain", "tags",
            "mission_requirements", "required_skills", "ai_summary", "ai_strategy",
            "ai_score", "difficulty", "difficulty_score", "win_probability",
            "urgency_score", "trust_score", "risk_score", "risk_level", "risk_flags",
            "logo_url",
        ]

        if existing:
            for field in update_fields:
                if field in opp_data:
                    setattr(existing, field, opp_data[field])
            existing.is_open = True
            updated += 1
            print(f"📝 Updated: {opp_data['title'][:55]}")
        else:
            opp = Opportunity(
                title=opp_data["title"],
                url=opp_data["url"],
                is_open=True,
                **{k: opp_data[k] for k in update_fields if k in opp_data},
            )
            db.add(opp)
            added += 1
            print(f"✅ Added:   {opp_data['title'][:55]}")

    db.commit()

    print("\n" + "=" * 60)
    print(f"✅ Comprehensive reseed complete!")
    print(f"   Updated: {updated}")
    print(f"   Added:   {added}")

    total = db.query(Opportunity).count()
    active = db.query(Opportunity).filter(
        Opportunity.is_open == True,
        or_(Opportunity.deadline == None, Opportunity.deadline >= datetime.now())
    ).count()
    print(f"\n📊 Database: {total} total, {active} active")

    db.close()


if __name__ == "__main__":
    main()
